# Use tall and fullscreen layouts
layouts:
  - column
  - fullscreen
  - row
  # - wide
  # - floating
  # - tall
  # - tall-right
  # - two-pane
  # - 3column-left
  # - middle-wide
  # - 3column-right
  # - 4column-left
  # - 4column-right
  # - widescreen-tall
  # - widescreen-tall-right
  # - bsp
# Add "command" to the default mods
mod1:
  - option
  # - shift
  # - command
mod2:
  - option
  - shift
  # - control
  # - command
# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
  mod: mod2
  key: z
# Enable focus-follows-mouse
mouse-follows-focus: false
focus-follows-mouse: false
# Add 10px margin between windows
window-margins: true
window-margin-size: 16
float-small-windows: true
mouse-swaps-windows: true
mouse-resizes-windows: true
cycle-layout:
  mod: mod1
  key: space
shrink-main:
  mod: mod1
  key: h
expand-main:
  mod: mod1
  key: l
focus-cw:
  mod: mod1
  key: j
focus-ccw:
  mod: mod1
  key: k
toggle-float:
  mod: mod1
  key: t
focus-screen-ccw:
  mod: mod1
  key: /,
focus-screen-cw:
  mod: mod1
  key: .
swap-screen-ccw:
  mod: mod2
  key: /,
swap-screen-cw:
  mod: mod2
  key: .
swap-cw:
  mod: mod2
  key: j
swap-ccw:
  mod: mod2
  key: k
# swap-cw:
#   mod: mod2
#   key: j
# swap-ccw:
#   mod: mod2
#   key: k
# swap-cw:
#   mod: mod2
#   key: j
# swap-ccw:
#   mod: mod2
#   key: k
throw-space-1:
  mod: mod2
  key: 1
throw-space-2:
  mod: mod2
  key: 2
throw-space-3:
  mod: mod2
  key: 3
throw-space-4:
  mod: mod2
  key: 4
throw-space-5:
  mod: mod2
  key: 5
throw-space-6:
  mod: mod2
  key: 6
throw-space-7:
  mod: mod2
  key: 7
throw-space-8:
  mod: mod2
  key: 8
throw-space-9:
  mod: mod2
  key: 9
throw-space-10:
  mod: mod2
  key: 0
floating: ['com.runningwithcrayons.Alfred', 'io.mpv', 'com.apple.TextEdit', 'com.colliderli.iina', 'com.apple.systempreferences']
